### PR TITLE
Feature: Add links to legend activities

### PR DESCRIPTION
**Pull request by dlh3**
Let me begin by saying that Node.js and Chrome extensions are definitely not my domain, so I am offering this PR on a best-effort basis.  

Commit 2ae6557 was necessary because event-stream@3.3.6 could not be found when I ran `npm install`.  I believe that version included a backdoor or other major vulnerability and was pulled from NPM.  I don't know if my approach here was correct (I suspect some of the changes in that commit are unwanted), but it unblocked me and allowed for the installation of dependencies.

The actual feature-related changes were pretty minimal, but I was unable to test them.  When I am using the published extension (from the Chrome Web Store), I can move the mouse out of the graph and the legend remains populated with the activities from whichever day I was on before moving the mouse out of the graph.  Strangely, this is not the case when I build and load the extension locally.  For my version (even before my changes), the legend clears when I move the mouse out of the grid.  No errors are logged in the dev console or chrome://extensions dashboard.  I also tried `npm run build:prod`, but that made no difference.

Anyways, the proposed feature is pretty straightforward.  It would be great if the activities in the fitness trend legend were links so a user could click to open that specific activity from the legend (rather than clicking the graph to open all activities on a given day, or scrolling down to find the activity in the table).  I keep finding myself trying to click an activity in the legend, so it just felt like the links should intuitively be there but they were missing.

Feel free to use part or all of this PR, or perhaps implement completely differently.  In any case, I'd love to see this change included in a future version.  

Thanks for the amazing project!

### CODE REVIEW

**Comment by dlh3** [comment]
Huh, how strange...  I removed my version of Elevate and re-enabled the official (Web Store) version.  Now it is exhibiting the same behaviour as my development version: the legend clears when the mouse moves out of the graph.

I know that this behaviour has definitely changed since yesterday before I started working on this, so I don't know what is going on... ¯\\_(ツ)_/¯

**Comment by thomaschampagne** [comment]
@dlh3 Thanks for your work.

Sorry but this feature is already coed here: https://github.com/thomaschampagne/elevate/blob/develop/plugin/app/src/app/fitness-trend/fitness-trend-graph/fitness-trend-graph.component.ts#L386

Right?!

**Comment by dlh3** [comment]
@thomaschampagne that's not the same thing.  Clicking on the Fitness Graph will open all activities for the viewedDay.  However, I have found many times where I had 3 or 4 activities on a day and wanted to open a particular activity.  Sure, I can click the day on the graph and close the extra tabs, but it feels like the user experience can be improved with links on the legend's activities.

Since the activities appear in the legend (or at least, a subset of the activities for that day appear in the legend), it feels intuitive that the user should be able to click on the activity in the legend to open it.

> For my version (even before my changes), the legend clears when I move the mouse out of the grid

As for the clearing legend behaviour that I mentioned, I could have sworn that the last date selected on the graph was persisted on mouseout before.  But I guess that was incorrect, because I realized that when I mouseout from the graph, it resets the legend to the current date (at [FitnessTrendGraphComponent#onGraphMouseOut(Date)](https://github.com/thomaschampagne/elevate/blob/develop/plugin/app/src/app/fitness-trend/fitness-trend-graph/fitness-trend-graph.component.ts#L419-L421)).  Since I was working on this PR around midnight, I guess the date rolled over, so the legend was resetting to the new date which had no activities.

I'm not sure what the reasoning was behind that behaviour, but it also seems counter-intuitive.  For example, it makes it impossible to select (mouseover) a day on the graph, then select and copy data from the legend (such as the activity names, HRSS/RSS, etc).  I've added an additional commit to this PR which comments out the FitnessTrendGraphComponent#onGraphMouseOut(Date) action, so that the last date viewed on the graph will remain in the legend when the user moves the mouse off the grid.

Please give this PR some further consideration.  Personally, I think these changes improve the user experience, based on my own experience with the extension.

Thanks again!

**Comment by thomaschampagne** [comment]
Hi @dlh3 

I worked on your PR this afternoon. I understood the function you added. You're right about this !

What i understand from your last comment it's more feature request around the legend persistence you need to make it clickable? But currently i can't merge this PR as is. We have to think more deeply the user friendly approach to make that possible.

Maybe we should close this PR and create new ticket?

Let me know how you see that

**Comment by thomaschampagne** [comment]
The idea could be: 

- If left click on day having multiples activities => a dialog pop in front and you can click the desired activity

- If left click on day having 1 activity=> open in strava directly.

Simple as that... What do you think?

**Comment by thomaschampagne** [comment]
I think a can do that quickly for the 6.8.1

**Comment by dlh3** [comment]
@thomaschampagne thanks for taking another look.

Personally, I preferred the clickable legend activities, but of course I'm biased toward my own solution.  I understand that part of your concern may have been that the legend has a max number of activities to show.  And of course, changing the graph's mouseout behaviour also had implications.

I've tried the dialog, and I think it is good enough to satisfy my intent for this PR.  Thanks again!

**Comment by thomaschampagne** [comment]
Consider this as a quick win :)

Merry Christmas!

Tom

**Pull request closed without merging**
