### PR TITLE
Support RSS Manual Runs (to close #742, #663 & #733) 

### PR DESCRIPTION
**Pull request by thomaschampagne**
@ahmism @ericwclymer @amokrunner @Strajk @RunOFX

This **final** merge request  supports **Running Stress Scores** of **manual runs** in fitness trend. If merged following tickets will be closed: #742, #663, #733

Here is a **debug test build**: [debug_test_build_85dae2f_2019-01-30-12-15.zip](https://github.com/thomaschampagne/elevate/files/2812282/debug_test_build_85dae2f_2019-01-30-12-15.zip)

If you have bugs or suggestions, just comment in that ticket.

Thanks for your help !

### CODE REVIEW

**Comment by ahmism** [comment]
Thanks @thomaschampagne! Unfortunately, my browser reports issues in chrome://extensions during activity synchronization. I see warnings for the manually entered runs ("Stream not found for activity ###"), which seem to come from ActivitiesSynchronizer.fetchWithStream, as well as a PositionError which is more opaque to me, as the reference is to line 73 of core/boot.bundle.js. If you agree, it looks like the original commit https://github.com/thomaschampagne/elevate/pull/751/commits/8c9772bb0c58c61247c71ea412096f67df9535cf is the source of the trouble. Not sure how you prefer to proceed when a stream isn't found for a manually entered run?

That said, the graphs look great :)

**Comment by uberlegit** [comment]
Mostly works great but generating some really insane outliers: https://pasteboard.co/HYStrMS.png
I believe these are all treadmill runs where I also ran the watch with a footpod, so there's associated pace data

**Comment by thomaschampagne** [comment]
@uberlegit So runs on your screenshots are not manual?

Can you provide me a backup to debug?

**Comment by thomaschampagne** [comment]
@uberlegit Yes it's here:
image

**Comment by thomaschampagne** [comment]
@uberlegit If you also have the backup on the real extension currently on chrome store, this will helps me to compare ;)

Thanks again !

**Comment by uberlegit** [comment]
[backups.zip](https://github.com/thomaschampagne/elevate/files/2814788/backups.zip)

**Comment by thomaschampagne** [comment]
@uberlegit Thanks !

I think you're using opera right? The version  (6.5.2) on opera store is actually outdated (unable to push new release for technicals reason).

Follow opera install from here https://thomaschampagne.github.io/elevate

**Comment by uberlegit** [comment]
firefox actually but didn't realize it was so far outdated, I do also have chrome. thanks!

**Comment by ahmism** [comment]
@thomaschampagne thanks for the debug test build, and sorry for the original sync problems. With this latest build, I can not in fact reproduce either of the errors I was having.

With the previous test build, here are the traces for the errors. The manual activity for the second one is here: https://www.strava.com/activities/2112332093. Again, the debug test build does not give me any errors, so if you're happy I'm happy. Thanks again!
object positionerror
stream not found

**Comment by thomaschampagne** [comment]
@ahmism Thanks. I don't how to fix that atm :/. It's too much risky to release RSS on manual runs currently.

That's not something i like to ask but... After settings a temporary password on your strava account, could you provide me your credentials by email? To trigger sync on my side and debug this...

Thanks

**Comment by thomaschampagne** [comment]
@uberlegit I may have fixed your insane RSS (https://pasteboard.co/HYStrMS.png) with the fix https://github.com/thomaschampagne/elevate/pull/751/commits/7f71d11515805ea96f602a8a1cd808b695aca026

You will find a test build here: [7f71d11_2019-01-31-12-40.zip](https://github.com/thomaschampagne/elevate/files/2817004/7f71d11_2019-01-31-12-40.zip)

Can you tell me if your problem is fixed?

Thanks

**Comment by uberlegit** [comment]
no crazy values anymore but no more estimation of manual runs either:
[from 7f71d11](https://pasteboard.co/HYZm1XM.png)
[from d5dae2f](https://pasteboard.co/HYZmDSe.png)

**Comment by thomaschampagne** [comment]
@uberlegit Strange.

With https://github.com/thomaschampagne/elevate/pull/751/commits/7f71d11515805ea96f602a8a1cd808b695aca026, I created a fake manual run:

image

And got...

image

Do you have a running FTP set for sure for the manual activities?

**Comment by uberlegit** [comment]
that was it — whoops. didn't set a running ftp after installing new extension. all final stress scores seem sane again.
thank you so much for this fix! as someone who does a lot of indoor training in the winter this is a huge help.

**Comment by thomaschampagne** [comment]
@uberlegit I'm glad to read this !

**Comment by ericwclymer** [comment]
I installed this shortly after you posted it a couple days ago and it all worked for me. I should have mentioned that at the time.

**Comment by thomaschampagne** [comment]
@ahmism Using your account/data and a **RFTP of 08:20/km = 13:25/mi = 500s/km**

I'm getting insane RSS results:

image

image

Just to know you have same strange results?

I continue to dig in.

**Comment by thomaschampagne** [comment]
@ahmism I created #754, #755, #756 to your case and potentially other users

**Comment by ericwclymer** [comment]
@thomaschampagne I installed that and gave it a quick test. I haven't noticed any errors or anything unreasonable with my data. Thanks again.

**Comment by thomaschampagne** [comment]
FYI here's v2.9.0 preview with all changes https://www.strava.com/clubs/242874/posts/4286957

**Pull request merged**
