### PR TITLE
Activity power curve: a start at #636

### PR DESCRIPTION
**Pull request by jon-smith**
My attempt at making a start at implementing a UI for a power curve for cycling activities.

It's currently very simple, showing power best efforts for a range arbitrary time points and only shows the power curve on a single activity; example image below:

image

Obviously a lot of scope for improvement - in particular it would be great to compare against historical bests, like the Strava example in #636, but I thought it would be good to get something simple in first.

My only real experience in web dev has been in React, so looking for some feedback for where I've gone wrong. And also this is my first PR outside of work! A few questions in particular:

- I feel like I hacked the scatter plot into `AbstractDataView` as it didn't really fit the current design, I did had some thoughts on how to improve this but would require a bit of refactoring which I didn't want to undertake without some feedback first
- I found a simpler way of modifying the tooltips (see `tooltips: { callback:` in `generateScatterLinePlot`), perhaps it makes sense to use the same for the histogram? Wasn't sure if refactoring for the sake of consistency was suitable
- I wanted to add a Watt/kg option and add that to the table but wasn't sure the best way of going about this - again would probably require some refactoring of how `AbstractDataView` is used
- The arbitrary time periods used could probably do with some refinement - see `defaultPowerCurveTimes` in `computeBestPowerSplits` - would be good to get some thoughts
- The x-axis labels aren't ideal, but you can get all the info you need from tooltips/table so I was happy with them for my purposes, if anyone has ideas for improvement that would be appreciated

Some further ideas, but probably not for this PR:
- Show average HR + cadence (plus other params) at each best effort interval - should be simple with some extension of the split calculator
- Further analysis at each best effort interval, showing the portion of the route and other params (like Strava's 'analysis' button on the power curve)
- Comparison to historical bests - wouldn't really know where to start with this, I guess there's somewhere that stores precalculated values of historical activities?

Any feedback would be great, and am happy to spend some more time on this to get it accepted as I know it's not quite there yet.

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@jon-smith Woow nice effort!! Sorry for the late reply. I will check this during christmas holidays

**Comment by jon-smith** [comment]
@thomaschampagne no worries, will have some time over the next few weeks so will be able to make any necessary adjustments.

**Comment by thomaschampagne** [comment]
Finally merged! Thanks for your awesome work. I edited few things before merging.

Do you have a twitter or something like that to credit your work?

**Comment by jon-smith** [comment]
Thanks! No twitter but the commit history is enough credit for me.

Are you still open to more PRs here? I was interested in extending this to compare against historical power curves and also adding other best effort curves, such as cadence, heart rate, and pace (for running) would be good to get some feedback on these ideas before doing anything.

**Comment by thomaschampagne** [comment]
Hi! Yes i'm totally open to this :). I will be able to merge them faster. Since i already analysed a similar work through this PR ;) 

Thanks again !!

**Pull request merged**
