### PR TITLE
#704 - adding a running performance index

### PR DESCRIPTION
**Pull request by lkj19zpdiDDe**
Calculate a running index. 

------

Improvements branch:
https://github.com/thomaschampagne/elevate/tree/lkj19zpdiDDe-feature/704-running-index

### CODE REVIEW

**Comment by thomaschampagne** [comment]
@lkj19zpdiDDe Thanks for this work! And sry for the delay of handling...

I'm currently on the code review of your pull request. 

For my concern and understanding, where did you find the formulas for running index?

In global settings there's no helper/explanations if we click on (i) icon.  Could you write the helper of your feature in a below comment? I will create the proper .md file  in the project under: https://github.com/thomaschampagne/elevate/tree/develop/plugin/app/src/assets/option-helpers

Nice work !

Thanks!

**Comment by lkj19zpdiDDe** [comment]
No problem! We're all busy. I'm also traveling for business and won't be back to my personal computer setup for development until May 29th or so.

As to the formula, @Chrisx68 provided it. Details on how he developed it are in the request thread - https://github.com/thomaschampagne/elevate/issues/704. I've also been using it and have found it to be predictive/good quality.

On the helper, I'm happy to do this once I'm back from my travel.

**Comment by lkj19zpdiDDe** [comment]
Alright, I've merged this with latests. Also, I took a look at the helper but couldn't figure that out in a few minutes. If you can add the text, that would be great. 

Here's what I wrote up for the helper text.

This option allows you to display a performance index for your runs. This index accounts for differences in your level of effort and distance so that you have a way to check how your peak performance is trending even if you’re doing different workouts.

**Comment by thomaschampagne** [comment]
It's merged! Thanks for  your work !!

I improved some little things after your commits

**Comment by thomaschampagne** [comment]
A test build from today is available here: https://thomaschampagne.github.io/elevate/#/builds

**Pull request merged**
