### PR TITLE
Reverse pace zones

### LINKED ISSUE #486: Run pace zones are reversed
Merci Thomas pour ton travail sur StravistiX! C'est *vraiment* apprécié!

The new running pace zones are reversed, meaning that the slowest paces are represented as the highest zones (Z6, Z7 etc..). Normally, the slower paces would be the lower zones. 

The running power zones are good. Very useful. Thanks.

### PR DESCRIPTION
**Pull request by interskh**
Attempting to fix #486

### CODE REVIEW

**Comment by interskh** [comment]
reverse_pace_zones
This is how it looks like now

**Comment by bevans76** [comment]
Looks good in the screen shot. However there still seems to be an issue with setting values for both running GAP and Pace zones within the Zone settings page: the ranges are reversed here and it does not allow you to properly set the zones. Thanks for looking at it.

**Comment by interskh** [comment]
Ah I know what I have missed. Let me fix it.

**Comment by thomaschampagne** [comment]
@interskh Let me know when it's ready to be reviewed along your fix

**Comment by bevans76** [comment]
Running Power looks good, thanks :-)
Running Pace and Grade Adjusted are still inverted. Remember that pace is the opposite to speed: High is slow (=Z1), low is fast (=Z7+/-x).

**Comment by bevans76** [comment]
Unfortunately yes...
stravistix pace

**Comment by interskh** [comment]
Ah, i guess it was because that you already have the custom zone setting. If you reset it, it would be fine.

I am not sure what is the best way to handle it. @thomaschampagne Is there something like a migration script that could run when a user upgrade the plugin?

**Comment by bevans76** [comment]
I have custom HR and Running Power zone settings (sorry for my prev blip there!).
I don't have GAP or Running Pace settings saved.
I've tried closing Strava and Stravistix tabs, and opening in a new chrome window.
so not sure how to solve...
thanks all for your efforts

**Comment by bevans76** [comment]
already tried that one...

**Comment by thomaschampagne** [comment]
@bevans76 Yes i usually handle the plugin migration through that file: https://github.com/thomaschampagne/stravistix/blob/develop/plugin/core/scripts/Installer.ts#L37

You have to upgrade version to 6.4.0 in https://github.com/thomaschampagne/stravistix/blob/develop/plugin/manifest.json#L6

You can simulate update by reloading the plugin. If you encounter some difficulties to do that, i will do it, just let me know

**Comment by thomaschampagne** [comment]
(I will start the review after the migration script done)

**Comment by bevans76** [comment]
I can’t read scripts, sorry.

I have 6.3.0 which is also the latest via the front end.

I guess I need to wait until 6.4.0 is loaded to the chrome store…?

**Comment by interskh** [comment]
@thomaschampagne i got the migration script ready :)

**Comment by thomaschampagne** [comment]
@interskh I didn't forgot your PR. Give me time ;)

**Comment by joubex** [comment]
I use 6.11.0 right now and still have the problem, so I don't want to begin importing my # 2400 workouts...
Is there any solution now? Thanks for your job anyway: I would be happy to contribute if it's working

**Pull request closed without merging**
