### PR TITLE
Feature/firefox

### PR DESCRIPTION
**Pull request by cedricdelpoux**
Make Strativix working in Firefox

### CODE REVIEW

**Comment by thomaschampagne** [comment]
Nice one!  We have a good start base ! I fast checked changes on my phone. We can't merge this "as is" for sure. It may not work on chrome. Some code has been deleted with unit tests to make it working on FF.

The build process for watch/build/package plugin for chrome and FF have to be done too. But not a big deal at all !

What do you think @MQuaresma ?

(Linked to #15)

**Comment by thomaschampagne** [comment]
@CodeNKasch Could you merge develop into this PR? PR has currently conflicts w/ develop.

On develop i simplified access to storage (local + sync) from **core** or **background** with this following class: https://github.com/thomaschampagne/stravistix/blob/develop/plugin/core/scripts/app-storage.ts

I tried to merge but i'm sure of what i'm doing with your code

Let me know if you need some help

Very thanks !

**Comment by Arrowana** [comment]
Do you need help with this one?
Seems like you messed up the branch history quite bad but it should be possible to redo the merge with the original set of changes

**Comment by thomaschampagne** [comment]
@Arrowana This could be a great help to me. Project structure (develop) will stay stable from now.

**Comment by leaskovski** [comment]
@thomaschampagne any news on this feature request?  Is this active, or being pushed out for the time being?  Its the only reason I still use chrome.

**Comment by timbmg** [comment]
+1

**Pull request closed without merging**
